### ISSUE TITLE
Find venue

### ISSUE THREAD

**Issue by MichaelKohler** [RustFestZurich/planning#6]

**Comment by gandro** [comment]
_If_ ETH is an option, they has fixed procedure and prices for conferences: https://www.ethz.ch/services/de/service/veranstaltungen-kongresse/bewilligungen.html

**Comment by gandro** [comment]
List of other possibles options: https://meeting.zuerich.com/de/meeting/zuerich-vielfalt-eventlokalitaeten?filters[135571]=375

Other options: Volkshaus, Glockenhaus

**Comment by dns2utf8** [comment]
Done
